MLIR: mlir::sparse_tensor::SparseTensorLoopEmitter Class Reference
mlir::sparse_tensor::SparseTensorLoopEmitter Class Reference
#include "Dialect/SparseTensor/Transforms/CodegenUtils.h"
Public Types
using OutputUpdater = function_ref< Value(OpBuilder &builder, Location loc, Value memref, Value tensor)>
Optional callback function to setup dense output tensors when initializing the loop emitter (e.g., to fill a dense output with zeros).
Public Member Functions
SparseTensorLoopEmitter (ValueRange tensors, StringAttr loopTag=nullptr, bool hasOutput=false, bool isSparseOut=false, ArrayRef< unsigned > topSort={})
Constructor: take an array of tensors inputs, on which the generated loops will iterate on.
void initializeLoopEmit (OpBuilder &builder, Location loc, OutputUpdater updater=nullptr)
Starts a loop emitting session by generating all the buffers needed to iterate tensors.
Value genAffine (OpBuilder &builder, AffineExpr a, Location loc)
Generates a list of operations to compute the affine expression.
void enterNewLoopSeq (OpBuilder &builder, Location loc, ArrayRef< size_t > tids, ArrayRef< size_t > dims)
Enters a new loop sequence, the loops within the same sequence starts from the break points of previous loop instead of starting over from 0.
void exitCurrentLoopSeq ()
Operation * enterLoopOverTensorAtDim (OpBuilder &builder, Location loc, size_t tid, size_t dim, MutableArrayRef< Value > reduc={}, bool isParallel=false, ArrayRef< size_t > extraTids={}, ArrayRef< size_t > extraDims={})
Emits loop over tensor_tid_dim, it assumes that loops between tensor_tid_[0, dim - 1] have already been generated.
Operation * enterFilterLoopOverTensorAtDim (OpBuilder &builder, Location loc, size_t tid, size_t dim, AffineExpr affine, MutableArrayRef< Value > reduc={})
void genDenseAffineAddressAtCurLevel (OpBuilder &builder, Location loc, size_t tid, size_t dim, AffineExpr affine)
Operation * enterCoIterationOverTensorsAtDims (OpBuilder &builder, Location loc, ArrayRef< size_t > tids, ArrayRef< size_t > dims, bool needsUniv, MutableArrayRef< Value > reduc={}, ArrayRef< size_t > extraTids={}, ArrayRef< size_t > extraDims={})
Emits a co-iteration loop over a set of tensors.
void exitCurrentLoop (RewriterBase &rewriter, Location loc, MutableArrayRef< Value > reduc={})
void getCoordinateArray (SmallVectorImpl< Value > &coords) const
Returns the array of coordinate for all the loop generated till now.
unsigned getCurrentDepth () const
Gets loop induction variable at the given level.
Value getLoopIV (size_t level) const
Gets loop induction variable at the given level.
const std::vector< std::vector< Value > > & getPidxs () const
Getters.
const std::vector< std::vector< Value > > & getCoord () const
const std::vector< std::vector< Value > > & getHighs () const
const std::vector< std::vector< Value > > & getPtrBuffer () const
const std::vector< std::vector< Value > > & getIdxBuffer () const
const std::vector< Value > & getValBuffer () const
Static Public Member Functions
constexpr static llvm::StringLiteral getLoopEmitterLoopAttrName ()
Detailed Description
Definition at line 341 of file CodegenUtils.h.
Member Typedef Documentation
OutputUpdater
using mlir::sparse_tensor::SparseTensorLoopEmitter::OutputUpdater = function_ref<Value(OpBuilder &builder, Location loc, Value memref, Value tensor)>
Optional callback function to setup dense output tensors when initializing the loop emitter (e.g., to fill a dense output with zeros).
Definition at line 345 of file CodegenUtils.h.
Constructor & Destructor Documentation
SparseTensorLoopEmitter()
SparseTensorLoopEmitter::SparseTensorLoopEmitter (ValueRange tensors, StringAttr loopTag = nullptr, bool hasOutput = false, bool isSparseOut = false, ArrayRef< unsigned > topSort = {}) explicit
Constructor: take an array of tensors inputs, on which the generated loops will iterate on.
The index of the tensor in the array is also the tensor id (tid) used in related functions. If isSparseOut is set, loop emitter assume that the sparse output tensor is empty, and will always generate loops on it based on the dim sizes. An optional array could be provided (by sparsification) to indicate the loop id sequence that will be generated. It is used to establish the mapping between affineDimExpr to the corresponding loop index in the loop stack that are maintained by the loop emitter.
Definition at line 97 of file CodegenUtils.cpp.
References mlir::sparse_tensor::Dense, mlir::sparse_tensor::getSparseTensorEncoding(), mlir::ValueRange::getType(), and mlir::sparse_tensor::isZeroRankedTensorOrScalar().
Member Function Documentation
enterCoIterationOverTensorsAtDims()
Operation * SparseTensorLoopEmitter::enterCoIterationOverTensorsAtDims (OpBuilder & builder, Location loc, ArrayRef< size_t > tids, ArrayRef< size_t > dims, bool needsUniv, MutableArrayRef< Value > reduc = {}, ArrayRef< size_t > extraTids = {}, ArrayRef< size_t > extraDims = {})
Emits a co-iteration loop over a set of tensors.
Definition at line 406 of file CodegenUtils.cpp.
References mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), genIndexLoad(), mlir::Block::getArgument(), mlir::Block::getArguments(), mlir::Builder::getIndexType(), mlir::Block::getNumArguments(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::sparse_tensor::isCompressedDLT(), mlir::sparse_tensor::isDenseDLT(), mlir::sparse_tensor::isSingletonDLT(), min(), and mlir::OpBuilder::setInsertionPointToStart().
enterFilterLoopOverTensorAtDim()
Operation * SparseTensorLoopEmitter::enterFilterLoopOverTensorAtDim (OpBuilder & builder, Location loc, size_t tid, size_t dim, AffineExpr affine, MutableArrayRef< Value > reduc = {})
Definition at line 332 of file CodegenUtils.cpp.
References mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), genAffine(), genIndexLoad(), mlir::AffineExpr::isa(), mlir::sparse_tensor::isDenseDLT(), and mlir::OpBuilder::setInsertionPointToStart().
enterLoopOverTensorAtDim()
Operation * SparseTensorLoopEmitter::enterLoopOverTensorAtDim (OpBuilder & builder, Location loc, size_t tid, size_t dim, MutableArrayRef< Value > reduc = {}, bool isParallel = false, ArrayRef< size_t > extraTids = {}, ArrayRef< size_t > extraDims = {})
Emits loop over tensor_tid_dim, it assumes that loops between tensor_tid_[0, dim - 1] have already been generated.
The function will also perform in-place update on the reduc vector to return the reduction variable used inside the generated loop.
Definition at line 256 of file CodegenUtils.cpp.
References mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), genIndexLoad(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::sparse_tensor::isCompressedDLT(), mlir::sparse_tensor::isDenseDLT(), mlir::sparse_tensor::isSingletonDLT(), and mlir::OpBuilder::setInsertionPointToStart().
enterNewLoopSeq()
void SparseTensorLoopEmitter::enterNewLoopSeq (OpBuilder & builder, Location loc, ArrayRef< size_t > tids, ArrayRef< size_t > dims)
Enters a new loop sequence, the loops within the same sequence starts from the break points of previous loop instead of starting over from 0.
e.g., { // loop sequence start. p0 = while(xxx) ... break p0
// Starts loop from p0 for (i = p0; i < end; i++) ... // loop sequence end. }
Definition at line 216 of file CodegenUtils.cpp.
References mlir::sparse_tensor::constantIndex().
exitCurrentLoop()
void SparseTensorLoopEmitter::exitCurrentLoop (RewriterBase & rewriter, Location loc, MutableArrayRef< Value > reduc = {})
Definition at line 711 of file CodegenUtils.cpp.
exitCurrentLoopSeq()
void mlir::sparse_tensor::SparseTensorLoopEmitter::exitCurrentLoopSeq () inline
Definition at line 389 of file CodegenUtils.h.
genAffine()
Value SparseTensorLoopEmitter::genAffine (OpBuilder & builder, AffineExpr a, Location loc)
Generates a list of operations to compute the affine expression.
Definition at line 228 of file CodegenUtils.cpp.
References mlir::Add, mlir::AffineExpr::cast(), mlir::Constant, mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), mlir::DimId, mlir::AffineExpr::getKind(), and mlir::Mul.
Referenced by enterFilterLoopOverTensorAtDim(), and genDenseAffineAddressAtCurLevel().
genDenseAffineAddressAtCurLevel()
void SparseTensorLoopEmitter::genDenseAffineAddressAtCurLevel (OpBuilder & builder, Location loc, size_t tid, size_t dim, AffineExpr affine)
Definition at line 399 of file CodegenUtils.cpp.
References genAffine().
getCoord()
const std::vector<std::vector<Value> >& mlir::sparse_tensor::SparseTensorLoopEmitter::getCoord () const inline
Definition at line 447 of file CodegenUtils.h.
getCoordinateArray()
void mlir::sparse_tensor::SparseTensorLoopEmitter::getCoordinateArray (SmallVectorImpl< Value > & coords) const inline
Returns the array of coordinate for all the loop generated till now.
Definition at line 428 of file CodegenUtils.h.
getCurrentDepth()
unsigned mlir::sparse_tensor::SparseTensorLoopEmitter::getCurrentDepth () const inline
Gets loop induction variable at the given level.
Definition at line 434 of file CodegenUtils.h.
getHighs()
const std::vector<std::vector<Value> >& mlir::sparse_tensor::SparseTensorLoopEmitter::getHighs () const inline
Definition at line 448 of file CodegenUtils.h.
getIdxBuffer()
const std::vector<std::vector<Value> >& mlir::sparse_tensor::SparseTensorLoopEmitter::getIdxBuffer () const inline
Definition at line 452 of file CodegenUtils.h.
getLoopEmitterLoopAttrName()
constexpr static llvm::StringLiteral mlir::sparse_tensor::SparseTensorLoopEmitter::getLoopEmitterLoopAttrName () inline static constexpr
Definition at line 457 of file CodegenUtils.h.
getLoopIV()
Value mlir::sparse_tensor::SparseTensorLoopEmitter::getLoopIV (size_t level) const inline
Gets loop induction variable at the given level.
Definition at line 437 of file CodegenUtils.h.
getPidxs()
const std::vector<std::vector<Value> >& mlir::sparse_tensor::SparseTensorLoopEmitter::getPidxs () const inline
Getters.
Definition at line 446 of file CodegenUtils.h.
getPtrBuffer()
const std::vector<std::vector<Value> >& mlir::sparse_tensor::SparseTensorLoopEmitter::getPtrBuffer () const inline
Definition at line 449 of file CodegenUtils.h.
getValBuffer()
const std::vector<Value>& mlir::sparse_tensor::SparseTensorLoopEmitter::getValBuffer () const inline
Definition at line 455 of file CodegenUtils.h.
initializeLoopEmit()
void SparseTensorLoopEmitter::initializeLoopEmit (OpBuilder & builder, Location loc, SparseTensorLoopEmitter::OutputUpdater updater = nullptr)
Starts a loop emitting session by generating all the buffers needed to iterate tensors.
Definition at line 140 of file CodegenUtils.cpp.
References mlir::OpBuilder::create(), mlir::linalg::createOrFoldDimOp(), mlir::Builder::getIndexAttr(), mlir::sparse_tensor::getIndexOverheadType(), mlir::sparse_tensor::getPointerOverheadType(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::sparse_tensor::isCompressedDLT(), mlir::sparse_tensor::isDenseDLT(), mlir::sparse_tensor::isSingletonDLT(), and mlir::sparse_tensor::toOrigDim().
The documentation for this class was generated from the following files:
lib/Dialect/SparseTensor/Transforms/CodegenUtils.h
lib/Dialect/SparseTensor/Transforms/CodegenUtils.cpp